package com.prepaidly.dto;

import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Journal Entry Response DTO
 * 
 * Data Transfer Object representing a journal entry in API responses. A journal entry
 * represents one month's recognition amount within an amortization schedule.
 * 
 * Journal entries are automatically generated when a schedule is created. Each entry
 * corresponds to one month in the schedule period and contains the amount to be
 * recognized for that month. Entries can be posted to Xero individually.
 * 
 * @see ScheduleResponse which includes a list of journal entries
 * @see PostJournalRequest for posting journal entries to Xero
 * @see com.prepaidly.controller.JournalController for journal endpoints
 */
@Data
public class JournalEntryResponse {
    /**
     * Unique identifier for the journal entry
     * 
     * Auto-generated by the database when the journal entry is created.
     * Used to reference the entry when posting to Xero.
     * Example: 1, 123, 456
     */
    private Long id;
    
    /**
     * ID of the schedule this journal entry belongs to
     * 
     * Links the journal entry to its parent amortization schedule.
     * Example: 10
     */
    private Long scheduleId;
    
    /**
     * Period date for this journal entry
     * 
     * The first day of the month this entry represents. Used as the journal date
     * when posting to Xero.
     * Example: "2025-01-01" (for January 2025)
     */
    private LocalDate periodDate;
    
    /**
     * Amount to be recognized for this period
     * 
     * The monthly recognition amount. For most entries, this is totalAmount / totalPeriods.
     * The last entry gets any remaining amount to account for rounding.
     * Example: 1000.00
     */
    private BigDecimal amount;
    
    /**
     * Xero manual journal ID
     * 
     * The ID of the manual journal entry created in Xero when this entry was posted.
     * Null if the entry has not been posted yet.
     * Example: "abc123-def456-ghi789"
     */
    private String xeroManualJournalId;
    
    /**
     * Xero journal number
     * 
     * The journal number assigned by Xero when this entry was posted.
     * Null if the entry has not been posted yet or if the number is not available.
     * Example: 8, 16, 17
     */
    private Integer xeroJournalNumber;
    
    /**
     * Posted status
     * 
     * Indicates whether this journal entry has been posted to Xero.
     * - true: Entry has been posted to Xero
     * - false: Entry has not been posted yet
     */
    private Boolean posted;
    
    /**
     * Timestamp when the journal entry was created
     * 
     * Automatically set when the journal entry is generated (when the schedule
     * is created). Format: ISO 8601 date-time.
     * Example: "2025-01-15T10:30:00"
     */
    private LocalDateTime createdAt;
    
    /**
     * Timestamp when the journal entry was posted to Xero
     * 
     * Set when the journal entry is successfully posted to Xero.
     * Null if the entry has not been posted yet.
     * Format: ISO 8601 date-time.
     * Example: "2025-01-20T14:30:00"
     */
    private LocalDateTime postedAt;
    
    /**
     * Timestamp when the journal entry was last updated
     * 
     * Automatically maintained by JPA when the entry is updated (e.g., when posted).
     * Format: ISO 8601 date-time.
     * Example: "2025-01-20T14:30:00"
     */
    private LocalDateTime updatedAt;
}

