package com.prepaidly.dto;

import com.prepaidly.model.Schedule;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Schedule Response DTO
 * 
 * Data Transfer Object representing a complete amortization schedule in API responses.
 * Contains all schedule information including generated journal entries and calculated
 * statistics.
 * 
 * This DTO is returned by schedule retrieval endpoints and includes:
 * - Schedule configuration (dates, amounts, accounts)
 * - All generated journal entries
 * - Calculated statistics (total periods, posted periods, remaining balance)
 * 
 * @see CreateScheduleRequest for creating schedules
 * @see com.prepaidly.controller.ScheduleController for schedule endpoints
 */
@Data
public class ScheduleResponse {
    /**
     * Unique identifier for the schedule
     * 
     * Auto-generated by the database when the schedule is created.
     * Example: 1, 123, 456
     */
    private Long id;
    
    /**
     * Xero tenant/organization ID
     * 
     * Identifies which Xero organization this schedule belongs to.
     * Example: "tenant-abc-123"
     */
    private String tenantId;
    
    /**
     * Optional Xero invoice ID
     * 
     * Links this schedule to a specific Xero invoice or bill, if provided.
     * Example: "invoice-xyz-789"
     */
    private String xeroInvoiceId;
    
    /**
     * Schedule type
     * 
     * Either PREPAID (prepaid expenses) or UNEARNED (unearned revenue).
     * 
     * @see com.prepaidly.model.Schedule.ScheduleType
     */
    private Schedule.ScheduleType type;
    
    /**
     * Start date of the schedule
     * 
     * The first date of the amortization period.
     * Example: "2025-01-01"
     */
    private LocalDate startDate;
    
    /**
     * End date of the schedule
     * 
     * The last date of the amortization period.
     * Example: "2025-03-31"
     */
    private LocalDate endDate;
    
    /**
     * Total amount to be amortized
     * 
     * The total amount distributed across all months in the schedule.
     * Example: 3000.00
     */
    private BigDecimal totalAmount;
    
    /**
     * Expense account code (for PREPAID schedules)
     * 
     * Chart of Accounts code for the expense account where expenses are recognized.
     * Only populated for PREPAID type schedules.
     * Example: "6000"
     */
    private String expenseAcctCode;
    
    /**
     * Revenue account code (for UNEARNED schedules)
     * 
     * Chart of Accounts code for the revenue account where revenue is recognized.
     * Only populated for UNEARNED type schedules.
     * Example: "4000"
     */
    private String revenueAcctCode;
    
    /**
     * Deferral account code
     * 
     * Chart of Accounts code for the deferral account (prepaid expenses asset or
     * unearned revenue liability account).
     * Example: "2000" or "2500"
     */
    private String deferralAcctCode;
    
    /**
     * User ID who created the schedule
     * 
     * Identifier for the user who created this schedule.
     * Example: 1
     */
    private Long createdBy;
    
    /**
     * Timestamp when the schedule was created
     * 
     * Automatically set when the schedule is created. Format: ISO 8601 date-time.
     * Example: "2025-01-15T10:30:00"
     */
    private LocalDateTime createdAt;
    
    /**
     * List of journal entries generated for this schedule
     * 
     * Contains all monthly journal entries that were automatically created when
     * the schedule was created. Each entry represents one month's recognition.
     * 
     * @see JournalEntryResponse
     */
    private List<JournalEntryResponse> journalEntries;
    
    /**
     * Remaining balance to be recognized
     * 
     * Calculated as: totalAmount - sum of amounts from posted journal entries.
     * Represents how much is still pending recognition.
     * Example: 2000.00
     */
    private BigDecimal remainingBalance;
    
    /**
     * Total number of periods (months) in the schedule
     * 
     * Calculated from the start and end dates. Represents the number of journal
     * entries generated.
     * Example: 3 (for Jan, Feb, Mar)
     */
    private Integer totalPeriods;
    
    /**
     * Number of periods that have been posted to Xero
     * 
     * Count of journal entries where posted = true. Represents how many months
     * have been recognized in Xero.
     * Example: 1 (if one journal entry has been posted)
     */
    private Integer postedPeriods;
}

