package com.prepaidly.dto;

import lombok.Data;

import java.time.LocalDateTime;

/**
 * User Response DTO
 * 
 * Data Transfer Object representing a user account in API responses. Contains
 * all user information that should be exposed to clients.
 * 
 * This DTO is returned by all user-related endpoints (create, get, update) to
 * provide a consistent response format. It includes the user's ID, email, and
 * creation timestamp.
 * 
 * @see CreateUserRequest for creating users
 * @see UpdateUserRequest for updating users
 * @see com.prepaidly.controller.UserController for user endpoints
 */
@Data
public class UserResponse {
    /**
     * Unique identifier for the user
     * 
     * Auto-generated by the database when the user is created. Used to reference
     * the user in other operations (update, delete, etc.).
     * 
     * Example: 1, 123, 456
     */
    private Long id;
    
    /**
     * User's email address
     * 
     * The email address serves as the unique identifier for the user account.
     * Must be unique across the system.
     * 
     * Example: "user@example.com"
     */
    private String email;
    
    /**
     * Timestamp when the user account was created
     * 
     * Automatically set by the system when the user is first created. Cannot be
     * modified after creation. Format: ISO 8601 date-time.
     * 
     * Example: "2025-01-15T10:30:00"
     */
    private LocalDateTime createdAt;
}

